### ISSUE TITLE
Attachments are not received from multipart messages

### ISSUE THREAD

**Issue by JereKuusela** [azanov/imapx#10]
Two scenarios where I have detected the issue:

1) Message has a message attachment. That message attachment may have attachments which are included in a second bodypart but not in attachments property.

2) Message with attachments is "Send again" so the original message will be in a second bodypart but its attachments are not loaded.

I guess the issue is that attachments are only acquired from the primary body part.

Does the next version help with these issues and is it being finished soon? This is kind of a big issue for me so please let me know if there is anything I can do to help.

**Comment by azanov** [comment]
Hi,

the next version handles these issues already. I plan to release a beta some time next week, once idle support is finished. Would be great if you can test it at that time. If you're not using idle and message uploads, you can already give it a try (see the [next branch](https://github.com/azanov/imapx/tree/next))

**Comment by JereKuusela** [comment]
That sounds good, thank you very much! I will test it next week.
