### ISSUE TITLE
Problems downloading *.CSV

### ISSUE THREAD

**Issue by TheUnreal0815** [azanov/imapx#11]
Hey Guys,
first of all thanks for your work ! Unfortunately I got a problem using imapX.dll with Powershell while downloading attachements.

When using "file.save (Downloadpath);" an attached csv is discovered with charset "US-ASCII" instead of its "UTF8" - no problem when using same csv as a txt for testing, but normal email contains csv. Is there a hint?
br
Sascha

**Comment by receiverbox** [comment]
Have you tried DownladRawMessage() method?
