### ISSUE TITLE
Regarding "Attachment" Issue in latest IMAPX dll (2.0.0.18)

### ISSUE THREAD

**Issue by PrakashGm** [azanov/imapx#14]
Hi Team ,

I hope you are doing good . 
                                  
Currently we are using IMAPX dll version (2.0.0.9) & we have started to upgrade with the latest version of 2.0.0.18, since i am facing with some issues 

Issue 1:  
               InLine pasted pictures/images can't able view in both existing/latest dll . ScreenShot attached for your reference ("imapx inline image")

![imapx inline image](https://user-images.githubusercontent.com/5630768/41718456-a89b227e-757a-11e8-80b1-102779270048.jpg)

Issue 2: 

While we are trying to send the email with ".EML" attachment , we are facing the issues in two scenarios

Scenario 1 :

          Any "eml" extension file , When it was sent through outlook with some content , i am not receiving the attachment with the lastest version .

Scenario 2 :

          If the ".eml" file(attached "example.zip" for your reference) contains  special characters , i am getting the error like 
("The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or 
a non-white space character among the padding characters") 

[example.zip](https://github.com/azanov/imapx/files/2123488/example.zip) .

Please kindly look into the above issues and let me know if u need more inputs from my end to solve this issue 
and  if any workaround available to solve this issue .

**Comment by jojastahl** [comment]
Issue 2 may be related to https://stackoverflow.com/questions/35088734/unexpected-characters-returned-when-reading-email-using-imapx ?

**Comment by jojastahl** [comment]
The proposed fix from stackoverflow seems to be in master at commit ae14d79edb46e6c3d4d66a66713ebea7f9ad440a. However this commit is after 2.0.0.18 release.

**Comment by fontanm** [comment]
hello

i am just investigating issue when email contains mixture of one inline file (for example png) and one attachment (for example pdf) - it results in weird thing where inline file is populated with attachment's data and attachment is not available at all.

My result so far is that the BODYSTRUCTURE is parsed incorrectly.

For example this one:
`BODYSTRUCTURE (((("text" "plain" ("charset" "UTF-8") NIL NIL "7bit" 34 1 NIL NIL NIL NIL)("text" "html" ("charset" "UTF-8") NIL NIL "7bit" 121 1 NIL NIL NIL NIL) "alternative" ("boundary" "000000000000250cce057b1a7834") NIL NIL NIL)("image" "png" ("name" "IMG_06102015_115656.png") "<ii_jopwobaf0>" NIL "base64" 316606 NIL ("inline" ("filename" "IMG_06102015_115656.png")) NIL NIL) "related" ("boundary" "000000000000250ccf057b1a7835") NIL NIL NIL)("application" "pdf" ("name" "Migration.pdf") "<f_jopwp7g91>" NIL "base64" 40998 NIL ("attachment" ("filename" "Migration.pdf")) NIL NIL) "mixed" ("boundary" "000000000000250cd0057b1a7836") NIL NIL NIL))
`
is parsed only into three parts:

1.1.1: text/plain
1.1.2: text/html
2: image/png

while I beleive that the correct result should be:

1.1.1: text/plain
1.1.2: text/html
1.2: image/png
2: application/pdf

BodyStructureParser is definitely bugged and will not work in many standard cases. For example in the case above it ends parsing on position 366 (at "related"("boundary"...) throwing attachment completely away

**Comment by Flem100** [comment]
@fontanm 

I have the same issue and you are right. As soon as there are no inline attachments, it works.
Any knowledge of an altenative to this library if he's not going to fix the issue?

**Comment by azanov** [comment]
Hi everyone,

it's been a long time since I last updated this project, nevertheless, there's ongoing work on a new version (https://github.com/azanov/imapx/tree/next). It has a completely refactored parser, and it fixes major issues with the handling of different parts of the messages.

Current plan is to finish a release by the end of this year. Should you require the fixes urgently and cannot wait, I can recommend https://github.com/jstedfast/MailKit

**Comment by Flem100** [comment]
@azanov 
Thank you so much for your quick reply! :)

I'll take a look at mailkit for now. Thanks again!

**Comment by fontanm** [comment]
> @fontanm
> 
> I have the same issue and you are right. As soon as there are no inline attachments, it works.
> Any knowledge of an altenative to this library if he's not going to fix the issue?

I have switched my service to MailKit now (it works as a charm) and I will keep an eye on this project and reuse it if this issue is fixed.

**Comment by fagalliu** [comment]
> hello
> 
> i am just investigating issue when email contains mixture of one inline file (for example png) and one attachment (for example pdf) - it results in weird thing where inline file is populated with attachment's data and attachment is not available at all.
> 
> My result so far is that the BODYSTRUCTURE is parsed incorrectly.
> 
> For example this one:
> `BODYSTRUCTURE (((("text" "plain" ("charset" "UTF-8") NIL NIL "7bit" 34 1 NIL NIL NIL NIL)("text" "html" ("charset" "UTF-8") NIL NIL "7bit" 121 1 NIL NIL NIL NIL) "alternative" ("boundary" "000000000000250cce057b1a7834") NIL NIL NIL)("image" "png" ("name" "IMG_06102015_115656.png") "<ii_jopwobaf0>" NIL "base64" 316606 NIL ("inline" ("filename" "IMG_06102015_115656.png")) NIL NIL) "related" ("boundary" "000000000000250ccf057b1a7835") NIL NIL NIL)("application" "pdf" ("name" "Migration.pdf") "<f_jopwp7g91>" NIL "base64" 40998 NIL ("attachment" ("filename" "Migration.pdf")) NIL NIL) "mixed" ("boundary" "000000000000250cd0057b1a7836") NIL NIL NIL)) `
> is parsed only into three parts:
> 
> 1.1.1: text/plain
> 1.1.2: text/html
> 2: image/png
> 
> while I beleive that the correct result should be:
> 
> 1.1.1: text/plain
> 1.1.2: text/html
> 1.2: image/png
> 2: application/pdf
> 
> BodyStructureParser is definitely bugged and will not work in many standard cases. For example in the case above it ends parsing on position 366 (at "related"("boundary"...) throwing attachment completely away

Hi fontanm,

I am having the same issue. Is this issue been solved or I must switch to MailKit library?

Thank you

**Comment by azanov** [comment]
Hi,

I didn't provide any support and updates for the ImapX project for a few years now. There simply has been no time. Considering this, I'd advise you to use Mailkit. It's well supported and fast.

Best,

Pavel

**Comment by fagalliu** [comment]
> Best

Thank you for your fast reply azanov.
