### ISSUE TITLE
Unable to recogonize the attachments in Gmail after google mailbox upgrade

### ISSUE THREAD

**Issue by AlbertArulPrakash** [azanov/imapx#15]
Team,

I was using imapx for sometime now and the code was able to recogonize the attachments stored in the email/draft in gmail. However, after the recent update from gmail (the new mailbox layout etc), imapx is not able to recogonize the attachments and all attachments are ignored message.Attachments.count is always zero. 

This is an issue for sure. Attached the sample images for the same. 
[EmailRetrievalCode.txt](https://github.com/azanov/imapx/files/2172416/EmailRetrievalCode.txt)

![codeattachmentzero](https://user-images.githubusercontent.com/1205707/42406406-981cdb26-81c4-11e8-9a4b-9e5b0ffa35ae.png)
![emailwithattachment](https://user-images.githubusercontent.com/1205707/42406407-984efb06-81c4-11e8-8eb3-9bff70be7789.png)

**Comment by juliocabrera1** [comment]
@IndiansIncredible  I recently made a test of this library and can find the attachments of gmail emails with a code similar as your but consuming the EmbeddedResources property of the message.
![capture](https://user-images.githubusercontent.com/7398466/43323783-f3dae074-9188-11e8-8a5b-068379a4d66d.PNG)

**Comment by AlbertArulPrakash** [comment]
Wow,
That worked. Yes the message.Attachments worked before and i was using it.
Suddenly it just stopped working.


Thanks,
Albert Arul Prakash
