### ISSUE TITLE
Support for tls > v1.0

### ISSUE THREAD

**Issue by sematro** [azanov/imapx#19]
I'm using imapx in version 2.0.0.18 in a powershell script.
At the moment it's using tls1.0 for transport encryption. 
Are you planning to implement tls1.2? Because the connection isn't possible when the server doesn't support tls1.0.
For security reasons it also would be better to use a higher tls version.

Thanks in advance.

**Comment by azanov** [comment]
Hi,

you can user TLS 1.2 by supplying it through the constructor:

```
var client = new ImapClient("imap.server.com", 993, SslProtocols.Tls12);
```

**Comment by sematro** [comment]
Thanks, it works now!
