### ISSUE TITLE
Reply-to is always null

### ISSUE THREAD

**Issue by pcapozzi** [azanov/imapx#24]
It seems that the ImapX.Message.Reply-to is always null.  I can check the Reply-to field in for example the 'show original' view of an email in gmail and it contains a value but this value is not in the ImapX.Message.Reply-to field when I check the same message downloaded by ImapX  There does not seem to be anything in the code that can affect this. While there are a number of enums in the ImapClient.Folders.Inbox.Messages.Download parameters, they do not seem to affect the resulting ImapX.Message.Reply-to.

**Comment by azanov** [comment]
@pcapozzi By default, the client will only request a minimal set of headers (See [1](https://github.com/azanov/imapx/blob/master/ImapX/Constants/MessageHeaderSets.cs#L11), [2](https://github.com/azanov/imapx/blob/master/ImapX/ClientBehavior.cs#L23))

You can always add additional headers by changing the `Behavior.RequestedHeaders` property of the client. 

```
/* .. Init client, authenticate .. */          
client.Behavior.RequestedHeaders = new[] {
            MessageHeader.From,
            MessageHeader.To,
            MessageHeader.Date,
            MessageHeader.Subject,
            MessageHeader.Cc,
            MessageHeader.ContentType,
            MessageHeader.ReplyTo // add reply-to header
};
```

You can also just set the property to null to always request all headers:

```
client.Behavior.RequestHeaders = null;
```

**Comment by pcapozzi** [comment]
Hi Pavel,

Thanks SO! much for the reply.  This solved a big problem for our app.

Great code.

Regards,

PatC
