### ISSUE TITLE
Problem to get attchaments

### ISSUE THREAD

**Issue by Daniel-iel** [azanov/imapx#3]
Someone could put this code on file imapx/ImapX/Parsing/BodyStructureParser.cs line 46 ? should be with the code DropExtensionData(); twice, to fix the problem of the attachments and inline attachments
![sem titulo](https://user-images.githubusercontent.com/12504110/32655512-00096b00-c5f5-11e7-8b27-1cf63772f465.png)

**Comment by azanov** [comment]
Hi Daniel,

there gonna be a new version of ImapX soon (see the https://github.com/azanov/imapx/tree/next branch) with a completely new parser which solves this problem.

**Comment by Daniel-iel** [comment]
Hello Azanov, 

I would like to know when the new version will be accessible on manage nuget packages ?

Best Regards.
