### ISSUE TITLE
how to connect to microsoft365 with oauth2 on powershell?

### ISSUE THREAD

**Issue by HomeOfSourceCode** [azanov/imapx#31]
I tried a lot things in powershell to connect to my exchange 365 mailbox, even ask ChatGPT AI.

All examples give me:
$authority = "https://login.microsoftonline.com/$tenantId/oauth2/v2.0/token"
$scope = "https://outlook.office365.com/.default"

$body = @{
    client_id     = $clientId
    client_secret = $clientSecret
    scope         = $scope
    grant_type    = "client_credentials"
}
$tokenResponse = Invoke-RestMethod -Uri $authority -Method Post -Body $body

$imapClient = New-Object ImapX.ImapClient("outlook.office365.com", 993, $true)
$imapClient.AuthenticateWithOAuth2($tokenResponse)
or
$imapClient.OAuth2Token = $tokenResponse.access_token

But both (.AuthenticateWithOAuth2 and .OAuth2Token) are no valid methods of imapx. I don't get it. Are there any examples available which are working? Or a documentations hwo to do this in powershell.

Thanks in advance

**Comment by azanov** [comment]
Hi,

the project is not being actively supported for a while already, please switch to MailKit (it's really, really good)
