### ISSUE TITLE
What is the license of this project?

### ISSUE THREAD

**Issue by kodfodrasz** [azanov/imapx#4]
Hi!

There is no LICENSE file in the root of the project, nor any README explaining the usage terms of the projects. Without this I cannot use the project, as I'm not granted any rights to do so.

Please provide a LICENSE to I can evaluate and maybe use the library in my project.
Github provides detailed description on setting the license in a way it can parse it: https://help.github.com/articles/licensing-a-repository/

Thanks!

**Comment by azanov** [comment]
Hi,

the project is licensed under Apache License 2.0. Please refer to the Codeplex page until the documentation is completely migrated to Github:

License: http://imapx.codeplex.com/license
Documentation: http://imapx.codeplex.com/documentation

**Comment by kodfodrasz** [comment]
Thanks!

**Comment by Jasonthurston** [comment]
I don't see any documentation at the link provided above (http://imapx.codeplex.com/documentation)

**Comment by emuuu** [comment]
@Jasonthurston Thats due the finalized shutdown of codeplex. As long as the docs aren't migrated to Github you can hit the "Download Archive"-button on codeplex. You'll get the whole archive including the wiki which lives in a bunch of html files which are not linked among each other which makes it quite annoying to handle but it works.

**Comment by azanov** [comment]
@Jasonthurston , yes, that's the only way currently. I am working on a new version (first results are in the [next](https://github.com/azanov/imapx/tree/next) branch), however, due to a tight schedule on other projects, I do not see a release coming before April. The docs will be updated along with the rollout of the new version.

**Comment by emuuu** [comment]
@azanov I parsed the codeplex doc (only plain text/html) and fixed the inline references. It's pretty handable as a offline documentation. Please let me now if it's ok to upload and post it here.

**Comment by azanov** [comment]
@emuuu That's great. If you don't mind, I can also upload it in a subfolder on imapx.org, just send me the zip to info@imapx.org

**Comment by emuuu** [comment]
I did send it to you and also created  [imapxDocumentation](https://github.com/emuuu/imapxDocumentation)

**Comment by azanov** [comment]
Thanks, the docs are now available at https://imapx.org/docs/
