### ISSUE TITLE
.net core

### ISSUE THREAD

**Issue by lucasBertola** [azanov/imapx#6]
Hi
Is there a version compatible with Core ? 
Thx

**Comment by azanov** [comment]
Hi,

the new release (https://github.com/azanov/imapx/tree/next) is compatible with .Net Standard 2.0, so can be used with .Net Core. Currently some things are still unfinished, however, I plan to make it production ready by April this year.

**Comment by lucasBertola** [comment]
Hi, thx for you response

Can you publish it on npm ? 
Maybe with "beta" or "pre-release" tag ? 

thx
