### ISSUE TITLE
getting attachments and folder list 

### ISSUE THREAD

**Issue by nocturneop15** [azanov/imapx#8]
2.0.0.18 .NET 4.52 and above - string ") IMAPX17 OK UID FETCH completed" is added to every attachment, resulting in errors in saving BASE64 encoded attachment. 7bit encoding simply adds this string to output text file 

2.0.0.18 .NET 4.5 and all below versions - returns empty Folders property 

All older versions were unable to get list of folders as well. 

Could this be fixed? Very similar topic is mentioned here: 
https://stackoverflow.com/questions/35088734/unexpected-characters-returned-when-reading-email-using-imapx

Environment to reproduce issue: Windows Server 2016, mailserver Kerio Connect 9.2.5, IMAPS, can provide test env access if necessary to debug

EDIT: added info

**Comment by nocturneop15** [comment]
As I found, these issues are fixed in 2.0.0.19, compiled from github source. 
Unfortunately 2.0.0.19 is not available on nuget.

**Comment by redxeagle** [comment]
@azanov would it be possible to get the 2.0.0.19 as nuget package on nuget?
